credentials:
  usernames:
    testuser:
      email: test@example.com
      name: testuser
      password: "$2b$12$2jGvs9HxHZ.bX82uhC7rg.bQz2gGTFxbio2ZsI3OIiyrMkX6EWnUW"
cookie:
  expiry_days: 1
  key: "random_key_12345"
  name: "legalassistant"
preauthorized:
  emails:
    - test@example.com
