cookie:
  expiry_days: 1
  key: random_key_12345
  name: legalassistant
credentials:
  usernames:
    '123':
      email: 123@gmail.com
      name: User
      password: $2b$12$d3yJuM/HZX0hYYmjszPoLewtva4VBZzZBiInAHmcCHL3KJjCOPTLu
    testuser:
      email: test@example.com
      name: testuser
      password: $2b$12$2jGvs9HxHZ.bX82uhC7rg.bQz2gGTFxbio2ZsI3OIiyrMkX6EWnUW
    user:
      email: user@gmail.com
      name: User
      password: $2b$12$AJOCvVPHun7NcuNo9cdSQu0lR8jDpmWtAoaWWkZA3Ib2BCuEvSjve
preauthorized:
  emails:
  - test@example.com
